# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jihoon's Website
email: jbaek796@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I occasionally enjoy writing out my thoughts. The process of writing helps me
  clarify and articulate my ideas. I hope you will find my writing useful, thought-provoking, or amusing. 

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jihoonbaek.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
